name: Alert Pager Duty

on: 
  workflow_dispatch:

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          curl --request POST \
               --url https://events.pagerduty.com/v2/enqueue \
               --header 'Content-Type: application/json' \
               --data '{
                  "payload": {
                      "summary": "Failed to run scheduled test for alcli",
                      "severity": "error",
                      "source": "https://github.com/alertlogic/alcli"
                  },
                  "routing_key": "551f474142b44702c00f0861398f614a",
                  "dedup_key": "alcli_failure",
                  "event_action": "trigger",
                  "links": [
                      {
                          "href": "https://github.com/alertlogic/alcli",
                          "text": "alcli repo"
                      }
                  ]
              }'