name: Build and sign windows artifacts
on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pywin32
          python -m pip install setuptools_scm[toml]>=3.4 setuptools>=42 wheel
      - name: Install windows requirements, prepare
        run: |
          powershell "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::TLS12"
          powershell "Set-ExecutionPolicy Unrestricted"
          powershell scripts/windows/install_inno_setup.ps1
          powershell scripts/windows/install_verpatch.ps1
          powershell scripts/windows/patch_json_schema.ps1
      - name: Build
        run: |
          python setup.py bdist_msi
          python scripts/windows/write_alcli_version.py
      - name: Sign
        env:
          CERT: ${{ secrets.CERT }}
          CERT_PWD: ${{ secrets.CERT_PWD }}
        run: |
          powershell scripts/windows/cleanup.ps1
          powershell scripts/windows/verpatch_cli.ps1
          powershell scripts/windows/load_sign_cert.ps1
          powershell scripts/windows/sign_cli.ps1
          powershell scripts/windows/build_inno_setup.ps1
          mv dist\alcli*.msi dist\alcli_setup.msi
          powershell scripts/windows/sign_cli_msi.ps1
