name: Run Tests and Release to PyPi
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    uses: ./.github/workflows/run_tests.yml
  setup:
    uses: ./.github/workflows/build_python.yml
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload --skip-existing dist/*
