name: Run Scheduled Tests

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every day at 16:00 UTC
    - cron:  '00 16 * * *'
  workflow_dispatch:

jobs:
  test_code:
    uses: ./.github/workflows/run_tests.yml
  test_python_build:
    uses: ./.github/workflows/build_python.yml
  test_windows_build:
    uses: ./.github/workflows/build_windows.yml
    secrets: inherit
  alert:
    runs-on: ubuntu-latest
    needs: [test_code, test_python_build, test_windows_build]
    if: failure()
    steps:
      - name: Alert Pager Duty of Failure
        run: |
          curl --request POST \
               --url https://events.pagerduty.com/v2/enqueue \
               --header 'Content-Type: application/json' \
               --data '{
                  "payload": {
                      "summary": "Failed to run scheduled test for alcli",
                      "severity": "error",
                      "source": "https://github.com/alertlogic/alcli"
                  },
                  "routing_key": "551f474142b44702c00f0861398f614a",
                  "event_action": "trigger",
                  "links": [
                      {
                          "href": "https://github.com/alertlogic/alcli",
                          "text": "alcli repo"
                      }
                  ]
              }'